//--------------------USUARIO-------------------
//agregar un usuario
###
post http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "said",
    "username":"said12",
    "contraseña":"said12",
    "email":"said12@gmail.com",
    "rol": "user"
}

//obtener todos los usuarios
###
GET http://localhost:9000/api/users HTTP/1.1

//obtener solo un usuario
###
GET http://localhost:9000/api/users/6489f6e2a907f09d655bc993 HTTP/1.1

//actualizar un usuario
###
PUT http://localhost:9000/api/users/64888753699675623c36e03b HTTP/1.1
Content-Type: application/json

{
    "username":"Jordan Bautista",
    "email":"jordan2407@gmail.com"
}

//removeer un usuario 
###
DELETE http://localhost:9000/api/users/648a259eacab664a7bd40fe4 HTTP/1.1

//------------------------------------PRODUCTO-------------------
//agregar un producto
###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto G22",
    "descripcion": "Negro ",
    "cantidad": 4,
    "categoria": "Smartphone",
    "precio": 20999,
    "existencia":5,
    "imagen": "motoG22.png"
}

//obtener todos los producto
###
GET http://localhost:9000/api/products HTTP/1.1

//obtener solo un producto
###
GET http://localhost:9000/api/products/6491fd7e759a46ee7e589442 HTTP/1.1

//actualizar un producto
###
PUT http://localhost:9000/api/products/6491fd7e759a46ee7e589442 HTTP/1.1
Content-Type: application/json

{
    "marca": "Samsung",
    "modelo": "Galaxy S21",
    "descripcion": "Teléfono inteligente de alta gama ",
    "cantidad": 4,
    "categoria": "Smartphone",
    "precio": 18999,
    "existencia":5,
    "imagen": "galaxyS21.png"
}

//removeer un producto 
###
DELETE http://localhost:9000/api/products/648b2e884c803beb4cc758ac HTTP/1.1



//------------Informacion Empresa-------------------

//agregar un Informacion Empresa
###
POST http://localhost:9000/api/empresaData HTTP/1.1
Content-Type: application/json

{
    "logo": "upn.png",
    "nombre": "M&G Innovaciones",
    "sobreNosotros": "Todo sobre nosotros",
    "avisoPrivacidad": "Todo sobre aviso de privacidad ",
    "direccion": "Carr. Huejutla - Chililico S/N",
    "telefono": "1238912366",
    "correo": "upn@gamil.com",
    "horario": "Lunes a domingo 7:00 a.m. a 7:00 p.m."
}

//obtener toda la Informacion Empresa
###
GET http://localhost:9000/api/empresaData HTTP/1.1

//obtener solo un Informacion Empresa
###
GET http://localhost:9000/api/empresaData/6494b45b0ec6abca9f56c124 HTTP/1.1

//actualizar un Informacion Empresa
###
PUT http://localhost:9000/api/empresaData/6494b5770ec6abca9f56c127 HTTP/1.1
Content-Type: application/json

{
    "logo": "upn.png",
    "sobreNosotros": "Todo sobre nosotrosooooo",
    "avisoPrivacidad": "Todo sobre aviso de privacidad ",
    "direccion": "Carr. Huejutla - Chililico S/N",
    "telefono": "1238912366",
    "correo": "upn@gamil.com",
    "horario": "Lunes a domingo 7:00 a.m. a 7:00 p.m."
}

//removeer un Informacion Empresa 
###
DELETE http://localhost:9000/api/EmpresaData/649ca7bbd20c47da173dc190 HTTP/1.1




//------------Informacion Redes sociales-------------------

//agregar un Informacion Redes sociales
###
POST http://localhost:9000/api/redesEmpresa HTTP/1.1
Content-Type: application/json

{
    "tipo": "whatsapp",
    "enlace": "whatsapp.http"

}

//obtener toda la Informacion Redes sociales
###
GET http://localhost:9000/api/redesEmpresa HTTP/1.1


//obtener solo un Informacion Redes sociales
###
GET http://localhost:9000/api/redesEmpresa/6494bcf712ed8e725661e6f6 HTTP/1.1

//actualizar un Informacion Redes sociales
###
PUT http://localhost:9000/api/redesEmpresa/64952e64e276d28dfaf4a30f HTTP/1.1
Content-Type: application/json

{
    "tipo": "instagram",
    "enlace": "instagram.http"
}

//removeer un Informacion Redes sociales 
###
DELETE http://localhost:9000/api/redesEmpresa/64952e64e276d28dfaf4a30f HTTP/1.1



//------------------------------------DATE PRODUCTO-------------------
//agregar un producto
###
POST http://localhost:9000/api/dateProducts HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto G52",
    "color": "negro",
    "descripcion": "telefono inteligente ",
    "cantidad": 4,
    "categoria": "Smartphone",
    "precio": 5099,
    "existencia":5,
    "imagen": "motoG52.png",
    "imagen2": "motoG52.png",
    "imagen3": "motoG52.png",
    "imagen4": "motoG52.png"
}

//obtener todos los producto
###
GET http://localhost:9000/api/dateProducts HTTP/1.1

//obtener solo un producto
###
GET http://localhost:9000/api/dateProducts/64a475648d9656267683514e HTTP/1.1

//actualizar un producto
###
PUT http://localhost:9000/api/dateProducts/64a475648d9656267683514e HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto G22",
    "color": "rojo",
    "descripcion": "telefono inteligente ",
    "cantidad": 4,
    "categoria": "Smartphone",
    "precio": 20999,
    "existencia":5,
    "imagen": "motoG22.png",
    "imagen2": "motoG23.png",
    "imagen3": "motoG24.png",
    "imagen4": "motoG25.png"
}

//removeer un producto 
###
DELETE http://localhost:9000/api/products/64a4765b849a13a947206763 HTTP/1.1


//------------------------------------Prueba-------------------
//agregar un producto
###
POST http://localhost:9000/api/datePrueba HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto G22",
    "imagen": "motoG22.png",
    "imagen2": "motoG23.png",
    "imagen3": "motoG24.png",
    "imagen4": "motoG25.png"
}

//obtener todos los producto
###
GET http://localhost:9000/api/datePrueba HTTP/1.1

//obtener solo un producto
###
GET http://localhost:9000/api/datePrueba/64a6d40bab17835033d0e3e6 HTTP/1.1

//actualizar un producto
###
PUT http://localhost:9000/api/datePrueba/6491fd7e759a46ee7e589442 HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto G22",
    "imagen": "motoG22.png",
    "imagen2": "motoG23.png",
    "imagen3": "motoG24.png",
    "imagen4": "motoG25.png"
}

//removeer un producto 
###
DELETE http://localhost:9000/api/datePrueba/64a6d40bab17835033d0e3e6 HTTP/1.1

