//--------------------USUARIO-------------------
//agregar un usuario
###
post http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "Admin",
    "username":"Admin",
    "contraseña":"123456789",
    "email":"Admin@gmail.com",
    "rol": "admin"
}

//obtener todos los usuarios
###
GET http://localhost:9000/api/users HTTP/1.1

//obtener solo un usuario
###
GET http://localhost:9000/api/users/6489f6e2a907f09d655bc993 HTTP/1.1

//actualizar un usuario
###
PUT http://localhost:9000/api/users/64888753699675623c36e03b HTTP/1.1
Content-Type: application/json

{
    "username":"Jordan Bautista",
    "email":"jordan2407@gmail.com"
}

//removeer un usuario 
###
DELETE http://localhost:9000/api/users/648a259eacab664a7bd40fe4 HTTP/1.1

//--------------------PRODUCTO-------------------
//agregar un producto
###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto G51 5G",
    "descripcion": "Dorado tornasol ",
    "cantidad": 4,
    "categoria": "Smartphone",
    "precio": 5699,
    "imagen": "motoG515G.png"
}

//obtener todos los producto
###
GET http://localhost:9000/api/products HTTP/1.1

//obtener solo un producto
###
GET http://localhost:9000/api/products/648b26f0a7f7aaa541ccf618 HTTP/1.1

//actualizar un producto
###
PUT http://localhost:9000/api/products/648b26f0a7f7aaa541ccf618 HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto e13",
    "descripcion": "Negro cosmico",
    "cantidad": 6,
    "categoria": "Electrónica",
    "precio": 2499,
    "imagen": "motoe13.png"
}

//removeer un producto 
###
DELETE http://localhost:9000/api/products/648b2946c6d5c5ad223d57b1 HTTP/1.1