//--------------------USUARIO-------------------
//agregar un usuario
###
post http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "Admin",
    "username":"Admin",
    "contraseña":"123456789",
    "email":"Admin@gmail.com",
    "rol": "admin"
}

//obtener todos los usuarios
###
GET http://localhost:9000/api/users HTTP/1.1

//obtener solo un usuario
###
GET http://localhost:9000/api/users/6489f6e2a907f09d655bc993 HTTP/1.1

//actualizar un usuario
###
PUT http://localhost:9000/api/users/64888753699675623c36e03b HTTP/1.1
Content-Type: application/json

{
    "username":"Jordan Bautista",
    "email":"jordan2407@gmail.com"
}

//removeer un usuario 
###
DELETE http://localhost:9000/api/users/648a259eacab664a7bd40fe4 HTTP/1.1

//------------------------------------PRODUCTO-------------------
//agregar un producto
###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
    "marca": "Motorola",
    "modelo": "Moto G22",
    "descripcion": "Negro ",
    "cantidad": 4,
    "categoria": "Smartphone",
    "precio": 20999,
    "existencia":5,
    "imagen": "motoG22.png"
}

//obtener todos los producto
###
GET http://localhost:9000/api/products HTTP/1.1

//obtener solo un producto
###
GET http://localhost:9000/api/products/6491fd7e759a46ee7e589442 HTTP/1.1

//actualizar un producto
###
PUT http://localhost:9000/api/products/6491fd7e759a46ee7e589442 HTTP/1.1
Content-Type: application/json

{
    "marca": "Samsung",
    "modelo": "Galaxy S21",
    "descripcion": "Teléfono inteligente de alta gama ",
    "cantidad": 4,
    "categoria": "Smartphone",
    "precio": 18999,
    "existencia":5,
    "imagen": "galaxyS21.png"
}

//removeer un producto 
###
DELETE http://localhost:9000/api/products/648b2e884c803beb4cc758ac HTTP/1.1